version: '3'
services:
  agent-x64:
    build:
      context: agents
      dockerfile: Dockerfile.trusty64
    hostname: trusty-64
  agent-x32:
    build:
      context: agents
      dockerfile: Dockerfile.trusty32
    hostname: trusty-32
  site:
    build:
      context: agents
      dockerfile: Dockerfile.site
    hostname: site
  deployer:
    build:
      context: agents
      dockerfile: Dockerfile.deployer
    hostname: deployer
    volumes:
      - /etc/private/deployer:/private
      - /home/http/files:/deploy/files
